- README.md
- demo/index.html
- demo/js/demo-four.jsx
- index.js
There was no support in the react module to define the returnFocus variable of focus-trap.
> Add support to disable returnFocus

- .eslintrc
- demo/js/demo-five.jsx
- demo/js/demo-four.jsx
- demo/js/demo-one.jsx
- demo/js/demo-three.jsx
- demo/js/demo-two.jsx
- index.js
- package.json
- yarn.lock
With the release of React 15.5 the use of CreateClass instead of ES6 classes and referencing PropTypes from React itself are marked as deprecation warnings and this will be removed in React 16.
These changes re-establishes full compatibility with the latest React releases.
> CreateClass and PropTypes refactor for React 15.5

- package.json
- test/__mocks__/requestAnimationFrame.js
- yarn.lock
Hi submitting this to make it work with React 16
> Update for React 16 

- src/focus-trap-react.js
Fixes https://github.com/davidtheclark/focus-trap-react/issues/18
I've run into a bug in IE 11 when used in an iFrame.  In that scenario, `document.activeElement` randomly returns an empty object if the element in question has a tab index.  Attempting to call `.focus()` on this empty object blows up with the following error in the console.
I'm submitting this PR to wrap the `.focus()` call in a try/catch to prevent the app from blowing up in this particular edge case with IE 11 and iFrames.
After the try/catch the app continues to work as expected minus returning focus and console logs the provided error as shown in this screen shot.
Please let me know if you need any more information or clarification and thank you for the library! 👍
> Check for focus before calling to fix IE 11/iFrame bug

- index.d.ts
This should resolve the issue described here: https://github.com/davidtheclark/focus-trap-react/pull/22#discussion_r159297573
cc: @TedDriggs
> adjust types so that props are available on the imported namespace

- package.json
Hi @davidtheclark
A recent update to the library no longer includes the type declarations. This PR adds the declaration file to the list of published files.
> fix: add typescript declaration file to publish files list

- README.md
- demo/js/demo-ffne.js
- demo/js/demo-special-element.js
- index.d.ts
- src/focus-trap-react.js
- test/activation.test.js
- test/deactivation.test.js
- test/dom.test.js
**UPDATED**:
Prior to this PR the `FocusTrap` component was expected to be passed in a `tag` property or default to a `div` tag.
Wrapping anything with a `<FocusTrap>` would cause a wrapping DOM node to be created (by default a `div`). This breaks CSS rules like when the parent of the focus-trapped element has a `display: flex` rule that only extends to its direct children. The newly created `div` tag would be the only direct child of the parent and the styling is broken.
This PR introduces a new API with new behavior. Instead of rendering a new tag or component which then acts as a focus trap around the user-provided child element, `<FocusTrap>` now just renders that child element directly while attaching focus trap behavior to that element.
In order for this to work the internally …
> New API with Single Required Child / Do Not Add Tags into DOM

- index.d.ts
`React.ReactElement<P>` is a generic and requires a type argument. This fixes that.
> fix broken generic in index.d.ts file

- package-lock.json
- package.json
- test/deactivation.test.js
Some of the latest `focus-trap` options are still not available for `focus-trap-react`. This PR makes them available, by updating to the latest version.
A test was also updated in order to prevent the activation to fail due to non-focusable element (a verification that wasn't being made in the past)
> Update focus-trap dependency to v5.1.0

- src/focus-trap-react.js
- Fixes https://github.com/davidtheclark/focus-trap-react/issues/50
- Allows mutable object refs, created by `React.createRef()`, to be used on the first child of the `<FocusTrap>` component
Here is a simple sample component that demonstrates the problem and the fix.
The problem is more prevalent when using the newer React Hooks, since most refs will be mutable object refs instead of callbacks.
```
import React from 'react';
import FocusTrap from 'focus-trap-react';
class Example extends React.PureComponent {
constructor(props) {
super(props);
this.ref = React.createRef();
}
componentDidMount() {
if (!this.ref.current) {
throw new Error('ref.current should be a reference to the button!');
}
}
render() {
return (
<FocusTrap>
<button ref={this.ref}>
Button
</button>
</FocusTrap>
);
}
}
```
> fix: Allow mutable object refs to be used for FocusTrap child

- .changeset/moody-apples-report.md
- README.md
Fixes #48 now that we're 2 maintainers taking over. Based on the
amount of activity and the stability of the code base, I think we
should be good for a bit.
> Remove call for maintainers

- .github/workflows/ci.yml
- cypress.json
- cypress/integration/focus-trap-demo.spec.js
- cypress/plugins/index.js
- cypress/support/index.js
- jest.config.js
- package.json
- yarn.lock
1. Initialize e2e testing framework using cypress.  
There are already some unit tests using **jest** which defaults its testing environment on `jsdom`. However `jsdom` could have some focus issues(or other glitches) that does not always work consistently with **real** browsers such as **chrome** and **firefox**.
1. Add a cypress test case based on the **defaults** demo.
1. **Firefox** should be working as well though the **cypress** v5 image does not work well on ci, complaining firefox is not supported 🤷‍♀️. The same docker image works perfectly with firefox at local. I may need to check that out at cypress docker image repo.
1. More cypress test cases based on demo.
> test: initialize e2e testing framework based on cypress

- demo/index.html
- demo/js/demo-autofocus.js
- demo/js/demo-defaults.js
- demo/js/demo-ffne.js
- demo/js/demo-special-element.js
And the 'special element' demo is now set to return focus
after deactivation, in particular to make it easier to
reproduce the issue that focus is NOT returned when deactivating
with the ESC key, which is the issue #54 is trying to fix.
> Set is-active style on trap demos, special-elem returns focus

- src/focus-trap-react.js
This PR adds support for a boolean to be passed to `allowOutsideClick` in the `focusTrapOptions` object. The changes were all suggested in #86 
**Update**: This PR is now a follow-up to https://github.com/focus-trap/focus-trap/pull/120
There are no unit tests for the `tailoredFocusTrapOptions`, so there are currently no tests in this PR. I would prefer that that not be the case.
I suggest we pull the transformation of `specifiedFocusTrapOptions` into `tailoredFocusTrapOptions` into a separate function that we can test in isolation. That way we can have confidence that we are tailoring the options correctly for use by [`focus-trap`](https://github.com/davidtheclark/focus-trap).
~~The [`README.md`](README.md) only makes [a blanket statement about …
> feat: Add boolean value support for allowOutsideClick option

- cypress/integration/focus-trap-demo.spec.js
Current e2e(cypress) test cases ensures some optional properties do work as expected but the very fundamental **focus-trapping** feature is not checked. So this PR add those crucial checks at e2e test cases which should expect that crucial behavior when the trap is active.
> test: add crucial focus trap on clicking check on cypress test

- .changeset/good-cups-collect.md
- package.json
This will cause the script (i.e. the build) to run:
1. when you run `yarn install` in the project after cloning the repo;
2. before publishing;
3. when installing the package from its git repo (an undocumented feature),
which is convenient if someone forks the repo to fix a bug and installs the
package from their fork until the bug fix is merged and a new package
version published.
Thanks to https://github.com/focus-trap/tabbable/pull/60 for pointing this out!
> prepublishOnly -> prepare

- README.md
Demo for `active` prop no longer existed or was renamed to `demo-special-element.js`
Thank you for your contribution! 🎉
Here are a few checks to help us make this the _best PR ever_ depending on the nature of your changes.
🥦 Please __replace these lines above with your PR message__, and remove the section below that doesn't apply:
👉 If any of these don't apply, please ~cross them out~.
👉 If any of these don't apply, please ~cross them out~.
> Fixes reference to non-existent demo

- .changeset/strong-emus-do.md
- cypress/integration/focus-trap-demo.spec.js
- src/focus-trap-react.js
- test/deactivation.test.js
This is a new fix for the issue identified in #54 after gaining
a better understanding of the issue.
The `returnFocusOnDeactivate` flag was being special-cased, but
not always, and the element to which focus should be returned,
which focus-trap-react attempts to manage on its own (see
class Constructor comment for reasoning), was not always correct.
For example, if the trap was deactivated, and then re-activated,
the 'last focused element before activation' wasn't updated at
the moment of re-activation, where it could've changed.
> Fix focus not always returning to expected element on active=false

- .changeset/yellow-carpets-talk.md
- package.json
- yarn.lock
This picks-up bug fixes in downstream tabbable 5.1.3
> Update focus-trap dependency to 6.1.4

- .changeset/young-crews-report.md
- README.md
- cypress/integration/focus-trap-demo.spec.js
- demo/index.html
- demo/js/demo-containerelements.js
- demo/js/index.js
- index.d.ts
- package.json
- src/focus-trap-react.js
- test/activation.test.js
- yarn.lock
This is WIP until the first PR is merged: https://github.com/focus-trap/focus-trap/pull/217, and the dependency of focus-trap is updated.
This is part 2 of the PR https://github.com/focus-trap/focus-trap/pull/217
---------------
Demo 1
Demo 2
> Add ability to pass containerElements to focus-trap

- .changeset/slow-adults-rhyme.md
- README.md
- cypress/integration/focus-trap-demo.spec.js
- demo/index.html
- demo/js/demo-containerelements-childless.js
- demo/js/index.js
- index.d.ts
- src/focus-trap-react.js
- test/activation.test.js
- test/dom.test.js
Only when `containerElements` are used.
> Make it possible to have `<FocusTrap />` without children

- SECURITY.md
- package.json
Recently, some folks from Drupal asked about security over on tabbable: https://github.com/focus-trap/tabbable/issues/136
As a result, I added a basic policy to tabbable and focus-trap, and throught we'd do the same with this repo.
> Add security policy

- .github/workflows/ci.yml
~- [ ] Issue being fixed is referenced.~
~- [ ] Unit test coverage added/updated.~
~- [ ] E2E test coverage added/updated.~
~- [ ] Prop-types added/updated.~
~- [ ] Typings added/updated.~
~- [ ] README updated (API changes, instructions, etc.).~
~- [ ] Changes to dependencies explained.~
~- [ ] Changeset added (run `yarn changeset` locally to add one, follow prompts).~
~- [ ] README instructions updated.~
- This is fixing cypress firefox issue on git action https://github.com/cypress-io/cypress-docker-images/issues/363 and also #104 
- Cypress container is updated to keep currency with `package.json` `devDependencies`
> upgrade e2e and enable firefox

- README.md
I've added a code coverage badge from Codecov to the README. This repo has 97% code coverage through the Jest unit tests, so we may as well flaunt it. Behold!
<details>
<br/>
- ~Issue being fixed is referenced.~
- ~Stated browser compatibility.~
- ~Stated React compatibility.~
- ~Unit test coverage added/updated.~
- ~E2E test coverage added/updated.~
- ~Prop-types added/updated.~
- ~Typings added/updated.~
- ~Changes to dependencies explained.~
- ~Changeset added (run `yarn changeset` locally to add one, and follow the prompts).~
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, …
> docs: adds a code coverage badge to the README

- cypress/integration/focus-trap-demo.spec.js
- demo/index.html
- demo/js/demo-autofocus.js
- demo/js/demo-containerelements-childless.js
- demo/js/demo-containerelements.js
- demo/js/demo-defaults.js
- demo/js/demo-ffne.js
- demo/js/demo-special-element.js
I've made several accessibility improvements to the demo site for semantic HTML correctness and also to help screen reader users. I've tested my fixes using the VoiceOver screen reader on a Mac and also with the axe Chrome extension.
The fixes include:
- use a `label` element to identify the autofocus input rather than plain text
- wrap all page content in a `main` element
- add an `aria-hidden="true"` attribute to the pointing finger icon so screen readers ignore it
- add contextual labels on the "activate trap" and "deactivate trap" buttons
- add spaces between a few words in the "containerElements" and "containerElements (no child)" demos
- use the `&&` operator to conditionally render the focus trap rather than an unnecessary ternary
- update the Cypress tests to still pass with the …
> docs: adds a11y improvements to the demo

- .changeset/eighty-wolves-switch.md
- src/focus-trap-react.js
Current implementation displays the following warning when a function is passed as the `clickOutsideDeactivates` prop. This was added in version `6.3.0` of focus-trap in [this commit](https://github.com/focus-trap/focus-trap/commit/a882d62532d0861cad5e76111f449eb3effe1106).
**Warning:**
`Warning: Failed prop type: Invalid prop `focusTrapOptions.clickOutsideDeactivates` of type `function` supplied to `FocusTrap`, expected `boolean`.`
It works as expected, but this is just an update to the propType definitions to prevent the error from displaying.
<details>
<br/>
- Unit test coverage …
> Remove clickOutsideDeactivates propType warning

- .changeset/cool-kiwis-float.md
- README.md
- src/focus-trap-react.js
- test/focus-trap-react.test.js
Fixes #268
Right now, this silently "fails" and appears to work, but it's actually not
working because the trap isn't activated, because it couldn't find a DOM
element for the Fragment.
This change throws an error if a child is given and it's a Fragment.
<details>
<br/>
- EXCEPTION: A Changeset is …
> Throw error if child is a Fragment

- .github/workflows/ci.yml
- package.json
- yarn.lock
This is a browser library. There's no need to test on two versions
of Node. It's not meant to run on Node anyway. We just use Node
to run JSDom for unit tests.
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package …
> Upgrade to Cypress 7.1.0 and drop testing on Node 12

- .github/workflows/ci.yml
Firefox may hang in CI when running Cypress tests. Increasing shared memory helps to avoid this. Also added timeout just to be sure since default is 6 hours, which unnecessarily burns CI minutes.
> Fix FF hang

- .changeset/quick-months-notice.md
- cypress/integration/focus-trap-demo.spec.js
- demo/index.html
- demo/js/demo-animated-dialog.js
- demo/js/demo-animated-trigger.js
- demo/js/demo-setReturnFocus.js
- demo/js/index.js
- src/focus-trap-react.js
- test/focus-trap-react.test.js
- Adding 2 new animated demos
- Adding the new values to PropTypes
- Adding support for `checkCanReturnFocus` and `onPostDeactivate`
- Adding Cypress tests for the new demos
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the …
> Adding new focus trap options support

- .changeset/selfish-dancers-wonder.md
- package.json
- src/focus-trap-react.js
- yarn.lock
Fixes #415
- `initialFocus` can now be false
- `escapeDeactivates` can now be a function that returns a boolean
Typings don't need updating because they are imported from focus-trap.
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that …
> [#415] Update to focus-trap 6.6.0

- .changeset/blue-peas-matter.md
- package.json
- yarn.lock
Fixes #452 (`initialFocus` option typings)
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not …
> Bump focus-trap dependency to v6.7.0

- .changeset/witty-moose-draw.md
- src/focus-trap-react.js
Code was accessing `document` global instead of first checking
for the `focusTrapOptions.document` setting.
<details>
<br/> …
> [#539] Fix incorrect reference to document

- .changeset/neat-sheep-cheer.md
- src/focus-trap-react.js
Fixes #539
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For …
> [#539] Delay trap creation until it should be active

- .changeset/fresh-rings-sip.md
- package.json
- yarn.lock
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, …
> Bump focus-trap to v6.7.2

- .changeset/khaki-pets-notice.md
- package.json
- yarn.lock
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, …
> Bump focus-trap to 6.7.3

- .changeset/olive-bears-relate.md
- README.md
- cypress/integration/focus-trap-demo.spec.js
- demo/index.html
- demo/js/demo-with-shadow-dom.js
- demo/js/index.js
- package.json
- src/focus-trap-react.js
- test/focus-trap-react.test.js
- yarn.lock
Adds a demo that uses open and closed shadows.
Does NOT add a test for this demo because of lack of support for
Shadow DOM in Cypress (see comment in focus-trap-demo.spec.js).
Adds a warning to the README about testing in JSDom, and fixes
all the JSDom-based tests to use `displayCheck='none'` to get
around JSDom limitations with new APIs used by tabbable in
v5.3.0.
<details>
<br/>
- Careful to test `typeof document/window !== 'undefined'` …
> Add shadow DOM support with ft v6.8.1

- .changeset/fifty-houses-occur.md
- .changeset/good-islands-enjoy.md
- .changeset/honest-mice-call.md
- .gitignore
- demo/js/demo-setReturnFocus.js
- demo/js/demo-special-element.js
- package.json
- src/focus-trap-react.js
- test/focus-trap-react.test.js
- yarn.lock
- Consistently call onDeactivate, onPostDeactivate, checkCanReturnFocus
These options were not being called consistently, particularly because
of the way focus-trap-react tries to participate in the trap's
deactivation process in order to control how focus is returned
(if the trap is configured to return focus after deactivation).
- Ensure an outside click permitted to deactivate the trap with the
`clickOutsideDeactivates=true` option is actually permitted to so
_and_ focus remains on the outside node clicked rather than returning
to the node that had focus prior to the trap being activated (which
is the default behavior).
- Required bump to focus-trap v6.9.0 for bug fixes and new features
to help with above fixes.
<details>
<br/>
__Please leave this …
> Fix multiple issues surrounding trap deactivation

- .changeset/shaggy-terms-relate.md
- package.json
- yarn.lock
This is in order to get tabbable v5.3.2 in downstream dependencies.
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of …
> Bump focus-trap to v6.9.1

- .changeset/tough-rice-check.md
- package.json
- yarn.lock
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, demo …
> Bump focus-trap to 6.9.3

- .changeset/funny-turkeys-sleep.md
- demo/js/demo-setReturnFocus.js
- src/focus-trap-react.js
- test/focus-trap-react.test.js
Fixes #705
When the `setReturnFocus` option is a function, it should get the
previously focused node prior to activation as its first parameter,
yet it was not because of the special handling in focus-trap-react
for trap deactivation.
<details>
<br/>
- Changes to dependencies …
> [#705] Fix setReturnFocus option as function not getting prev node

- .changeset/fifty-experts-judge.md
- package.json
- yarn.lock
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, demo …
> Bump focus-trap to v6.9.4 for typings fix

- .changeset/shy-terms-fold.md
- package.json
- src/focus-trap-react.js
Fixes #77
Fixes #704
For the longest time, since before I took over, we were filtering
specified containers through `ReactDOM.findDOMNode()`, but why?
The configured trap containers (via the `containerElements` prop)
must be elements already, which means they must already be rendered,
which means there's no point in passing them through `findDOMNode()`
to find an underlying DOM element because they aren't React elements
in the first place.
The removal of this call should mean that React Strict Mode will
finally be OK with focus-trap-react.
Note it's still possible to render a focus trap with a single React
element child. That works fine, and never needed `findDOMNode()`
anyway. We were already using a callback ref to get its element
to then auto-configure that element as the single …
> [#77] Finally drop use of findDOMNode()

- .changeset/happy-knives-glow.md
- demo/index.html
- demo/js/demo-special-element.js
- package.json
- src/focus-trap-react.js
- yarn.lock
Fixes #720
In React strict mode, the trap gets immediately unmounted and remounted after
first mount. The trap deactivates automatically on unmount, so on remount,
we try to restore the trap to its previous active/paused state based on
the component's existing state.
React does not re-render the component, nor does it call callback refs
again, so we have no choice but to assume the DOM hasn't changed and
the existing trap's container elements are still in the DOM...
Way to go React for strict mode violating the assumption of
`componentWillUnmount()`, "Once a component is unmounted, it will
never be mounted again." Not a fan.
Also bumped react-dom to 18.2.0 since react was already there, and
set NODE_ENV for different builds.
<details>
<br/>
__Please leave …
> [#720] Add strict mode compatibility

- .changeset/angry-candles-hug.md
- package.json
- src/focus-trap-react.js
- yarn.lock
See changeset for details.
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package …
> Update focus-trap to v7.0.0, tabbable to v6.0.0

- .changeset/kind-doors-tie.md
- README.md
Fixes #773
If a component is used as the trap's child, it must forward refs,
which implies it cannot be a class-based component.
<details>
<br/>
- EXCEPTION: A …
> [#773] Add note about single child components

- .changeset/hot-students-kneel.md
- README.md
Fixes #796
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For …
> [#796] Add help for Strict Mode in README

- .changeset/rich-dingos-type.md
- package.json
- src/focus-trap-react.js
- yarn.lock
Add missing trapStack option from 7.1.0 and new isKeyForward/isKeyBackward options from 7.2.0.
<details>
<br/>
- EXCEPTION: A Changeset is not required if the …
> Bump focus-trap to 7.2.0

- .changeset/grumpy-pumas-complain.md
- package.json
- yarn.lock
Fixes #905 
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For …
> Bump focus-trap to v7.3.1 and tabbable to v6.1.1

- .changeset/loud-peaches-share.md
- package-lock.json
- package.json
Fixes #986
Note that tabbable was already bumped separately earlier today by Dependabot in #989.
<details>
<br/>
- EXCEPTION: A Changeset is not required if …
> [#986] Bump focus-trap to v7.4.1 for nwsapi patch in tabbable v6.1.2

- .changeset/tall-ways-tie.md
- package-lock.json
- package.json
Fixes #962 
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For …
> Bump focus-trap to v7.4.3

- .changeset/afraid-terms-sparkle.md
- package-lock.json
- package.json
This gives access to the new positive `tabindex` support for single-container traps in focus-trap.
<details>
<br/>
- EXCEPTION: A Changeset is not required if …
> Bump focus-trap to v7.5.1 and tabbable to v6.2.0

- .changeset/twenty-bees-scream.md
- package-lock.json
- package.json
Fixes a bug in Safari with `Array.findLast()` not being defined.
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of …
> Bump focus-trap to v7.5.2

- .changeset/mean-dolphins-reply.md
- package-lock.json
- package.json
> Bump focus-trap to 7.5.3 for typings fix

- .changeset/grumpy-shirts-count.md
- package-lock.json
- package.json
> Bump focus-trap to 7.5.4 for shadow DOM fix

- .changeset/eight-pans-trade.md
- package-lock.json
- package.json
> Bump focus-trap to v7.6.1

- .changeset/hot-planes-roll.md
- .eslintrc.js
- .gitignore
- README.md
- index.d.ts
- package-lock.json
- package.json
- src/focus-trap-react.js
focus-trap-react was already "ready" for React 19. All that was necessary was to drop `prop-types`, which has been removed as a dependency.
It's also time to move forward and stop supporting ancient versions of React. Therefore, the minimum supported version of React will now be 18.0.0, and I intend for that remain one version behind the latest version going forward, provided the gap between the two is reasonably surmountable.
<details>
<br/>
- E2E …
> MVP support for React 19

- .changeset/brown-buttons-do.md
- README.md
- demo/js/demo-animated-dialog.js
- demo/js/demo-animated-trigger.js
- demo/js/demo-autofocus.js
- demo/js/demo-containerelements-childless.js
- demo/js/demo-containerelements.js
- demo/js/demo-defaults.js
- demo/js/demo-ffne.js
- demo/js/demo-iframe.js
- demo/js/demo-setReturnFocus.js
- demo/js/demo-special-element.js
- demo/js/demo-with-shadow-dom.js
- index.d.ts
- src/focus-trap-react.js
- test/focus-trap-react.test.js
Fixes #1396
My original intent was to remove the default export (a breaking change) as part of the major 11.0.0 release but I totally flopped on that by not also actually providing the named export in the code.
Now that the major release ship has sailed, this change fixes the types by reinstating the default export in the typings but marking it deprecated, while also providing the new named export alternative as the way forward.
<details>
<br/>
- E2E …
> Fix v11.0.0 types that removed the default export

- .changeset/tiny-ghosts-swim.md
- package-lock.json
- package.json
> Bump focus-trap to v7.6.4
